import React, { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowUpRight, CreditCard, FileText, Receipt, ShieldCheck, Ticket, Wrench, Zap } from 'lucide-react-native';
import { api } from '../../../src/lib/api';
import { useFetch } from '../../../src/hooks/useFetch';
import { formatDate, formatINR, formatNumber } from '../../../src/lib/formatters';
import { Badge, Card, DetailRow, EmptyState, ErrorState, HeaderButton, Loading, Screen, StatCard } from '../../../src/components/ui';
import { useAuth } from '../../../src/context/AuthContext';

type ProjectTab = 'overview' | 'technical' | 'financials' | 'activity';

export default function ProjectDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const state = useFetch(() => api.getProject(String(id)), [id]);
  const data = state.data;
  const item = data?.project;
  const { hasPermission } = useAuth();
  const [tab, setTab] = useState<ProjectTab>('overview');
  const payments = data?.payments ?? []; const expenses = data?.expenses ?? []; const warranties = data?.warranties ?? []; const invoices = data?.invoices ?? []; const complaints = data?.complaints ?? []; const documents = data?.documents ?? [];
  const received = payments.reduce((sum: number, payment: any) => sum + Number(payment.amount || 0), 0);
  const cost = expenses.reduce((sum: number, expense: any) => sum + Number(expense.amount || 0), 0);

  return <Screen title={item?.projectName || 'Project'} subtitle={item?.customId} onBack={() => router.back()} action={item && hasPermission('projects.edit') ? <HeaderButton label="Edit" onPress={() => router.push({ pathname: '/project-form', params: { id: item.id } })} /> : undefined} refreshing={state.isRefreshing} onRefresh={state.refresh}>
    {state.isLoading ? <Loading /> : state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : item ? <>
      <Card className="bg-[#0b1b31] border-[#173554] p-5"><View className="flex-row items-start"><View className="w-11 h-11 rounded-2xl bg-amber-400 items-center justify-center"><Zap size={21} color="#0b1b31" /></View><View className="flex-1 ml-3"><Text className="text-lg font-extrabold text-white">{item.projectName}</Text><Text className="text-xs text-slate-300 mt-1">{data.customer?.name || 'Customer'} • {item.capacityKw || 0} kW</Text></View><Badge text={item.status || 'Draft'} tone={/complete|installed/i.test(item.status || '') ? 'green' : 'amber'} /></View>{(hasPermission('payments.create') || hasPermission('expenses.create')) ? <View className="flex-row gap-2 mt-5">{hasPermission('payments.create') ? <Action label="Record payment" icon={<CreditCard size={15} color="#34d399" />} onPress={() => router.push({ pathname: '/payment-form', params: { projectId: item.id } })} /> : null}{hasPermission('expenses.create') ? <Action label="Log expense" icon={<Receipt size={15} color="#fda4af" />} onPress={() => router.push({ pathname: '/expense-form', params: { projectId: item.id, customerId: item.customerId } })} /> : null}</View> : null}</Card>
      <View className="flex-row gap-3"><View className="flex-1"><StatCard label="Contract" value={formatINR(item.finalDealAmount || item.dealAmount)} /></View><View className="flex-1"><StatCard label="Received" value={formatINR(item.totalReceived ?? received)} accent="text-emerald-700" /></View></View>
      <View className="flex-row gap-3"><View className="flex-1"><StatCard label="Balance" value={formatINR(item.pendingBalance)} accent={(item.pendingBalance ?? 0) > 0 ? 'text-amber-600' : 'text-emerald-700'} /></View><View className="flex-1"><StatCard label="Actual profit" value={formatINR(item.actualProfit ?? Number(item.finalDealAmount || 0) - cost)} accent="text-blue-700" /></View></View>
      <TabBar tab={tab} onChange={setTab} counts={{ payments: payments.length, expenses: expenses.length, support: complaints.length + warranties.length }} />
      {tab === 'overview' ? <Overview item={item} data={data} hasPermission={hasPermission} onNavigate={path => router.push(path as never)} /> : null}
      {tab === 'technical' ? <Technical item={item} /> : null}
      {tab === 'financials' ? <Financials item={item} payments={payments} expenses={expenses} onNavigate={path => router.push(path as never)} /> : null}
      {tab === 'activity' ? <Activity data={{ invoices, warranties, complaints, documents }} /> : null}
    </> : null}
  </Screen>;
}

function Action({ label, icon, onPress }: { label: string; icon: React.ReactNode; onPress: () => void }) { return <Pressable onPress={onPress} className="flex-1 min-h-11 rounded-xl bg-[#132a47] border border-[#29415f] px-2 flex-row items-center justify-center active:bg-[#1a3a5e]"><View>{icon}</View><Text className="text-[10px] font-bold text-white ml-1.5" numberOfLines={1}>{label}</Text></Pressable>; }

function TabBar({ tab, onChange, counts }: { tab: ProjectTab; onChange: (tab: ProjectTab) => void; counts: { payments: number; expenses: number; support: number } }) {
  const tabs: { key: ProjectTab; label: string; count?: number }[] = [{ key: 'overview', label: 'Overview' }, { key: 'technical', label: 'Technical' }, { key: 'financials', label: 'Financials' }, { key: 'activity', label: 'Activity', count: counts.payments + counts.expenses + counts.support }];
  return <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mb-4"><View className="flex-row gap-2">{tabs.map(item => <Pressable key={item.key} onPress={() => onChange(item.key)} className={`px-4 py-2.5 rounded-xl border ${tab === item.key ? 'bg-amber-50 border-amber-300' : 'bg-white border-slate-200'}`}><Text className={`text-xs font-bold ${tab === item.key ? 'text-amber-800' : 'text-slate-500'}`}>{item.label}{item.count != null ? ` (${item.count})` : ''}</Text></Pressable>)}</View></ScrollView>;
}

function Overview({ item, data, hasPermission, onNavigate }: { item: any; data: any; hasPermission: (permission: string) => boolean; onNavigate: (path: string) => void }) {
  const canActions = hasPermission('warranties.create') || hasPermission('invoices.create') || hasPermission('complaints.create');
  return <><Card><Text className="text-sm font-extrabold text-slate-900 mb-2">Installation site & customer</Text><DetailRow label="Customer" value={data.customer?.name} /><DetailRow label="Phone" value={data.customer?.mobile} /><DetailRow label="Address" value={[item.installationAddress, item.city, item.state, item.pincode].filter(Boolean).join(', ')} /><DetailRow label="Booking date" value={formatDate(item.bookingDate)} /><DetailRow label="Start date" value={formatDate(item.startDate)} /><DetailRow label="Completion" value={formatDate(item.completionDate)} /><DetailRow label="Net metering" value={item.netMeteringStatus} /></Card>{canActions ? <Card><View className="flex-row items-center justify-between mb-2"><Text className="text-sm font-extrabold text-slate-900">Project actions</Text><ArrowUpRight size={17} color="#94a3b8" /></View>{hasPermission('warranties.create') ? <Pressable onPress={() => onNavigate('/warranty-form')} className="flex-row items-center py-3 border-b border-slate-100"><ShieldCheck size={17} color="#059669" /><Text className="flex-1 ml-3 text-xs font-bold text-slate-800">Issue warranty card</Text><ArrowUpRight size={15} color="#94a3b8" /></Pressable> : null}{hasPermission('invoices.create') ? <Pressable onPress={() => onNavigate('/invoice-form')} className="flex-row items-center py-3 border-b border-slate-100"><FileText size={17} color="#2563eb" /><Text className="flex-1 ml-3 text-xs font-bold text-slate-800">Create project invoice</Text><ArrowUpRight size={15} color="#94a3b8" /></Pressable> : null}{hasPermission('complaints.create') ? <Pressable onPress={() => onNavigate('/ticket-form')} className="flex-row items-center pt-3"><Wrench size={17} color="#e11d48" /><Text className="flex-1 ml-3 text-xs font-bold text-slate-800">Open service ticket</Text><ArrowUpRight size={15} color="#94a3b8" /></Pressable> : null}</Card> : null}</>;
}

function Technical({ item }: { item: any }) {
  return <><Card><Text className="text-sm font-extrabold text-slate-900 mb-2">System hardware</Text><DetailRow label="Plant capacity" value={`${formatNumber(item.capacityKw)} kW`} /><DetailRow label="Panels" value={`${item.panelsCount || 0} • ${item.panelBrand || 'Not specified'} ${item.panelModel || ''}`} /><DetailRow label="Panel serials" value={item.panelSerialNumbers} /><DetailRow label="Inverter" value={`${item.inverterBrand || 'Not specified'} ${item.inverterModel || ''}`} /><DetailRow label="Inverter serial" value={item.inverterSerial} /><DetailRow label="Battery" value={item.batteryInstalled ? `${item.batteryBrand || ''} ${item.batteryModel || ''} (${item.batteryCapacity || 'capacity not set'})` : 'On-grid / no battery'} /><DetailRow label="Structure" value={item.structureType} /><DetailRow label="Mounting" value={item.mountingType} /></Card><Card><Text className="text-sm font-extrabold text-slate-900 mb-2">Grid & configuration</Text><DetailRow label="Installation type" value={item.installationType} /><DetailRow label="System config" value={item.systemConfiguration} /><DetailRow label="UPPCL account" value={item.uppclAccountNo} /><DetailRow label="Net metering" value={item.netMeteringStatus} /><DetailRow label="Plan package" value={item.planPackage} /></Card>{item.technicalNotes ? <Card><Text className="text-[10px] font-bold tracking-wide text-slate-400 mb-2">TECHNICAL NOTES</Text><Text className="text-sm leading-5 text-slate-700">{item.technicalNotes}</Text></Card> : null}</>;
}

function Financials({ item, payments, expenses, onNavigate }: { item: any; payments: any[]; expenses: any[]; onNavigate: (path: string) => void }) {
  return <><Card><Text className="text-sm font-extrabold text-slate-900 mb-2">Financial breakdown</Text><DetailRow label="Base deal" value={formatINR(item.dealAmount)} /><DetailRow label="Discount" value={formatINR(item.discount)} /><DetailRow label="GST" value={formatINR(item.taxGst)} /><DetailRow label="Final deal" value={formatINR(item.finalDealAmount)} /><DetailRow label="Received" value={formatINR(item.totalReceived)} /><DetailRow label="Pending" value={formatINR(item.pendingBalance)} /><DetailRow label="Expenses" value={formatINR(expenses.reduce((sum: number, expense: any) => sum + Number(expense.amount || 0), 0))} /><DetailRow label="Actual profit" value={formatINR(item.actualProfit)} /></Card><Card><View className="flex-row items-center justify-between mb-2"><Text className="text-sm font-extrabold text-slate-900">Collections</Text><Pressable onPress={() => onNavigate('/payment-form')}><Text className="text-xs font-bold text-amber-700">Add payment</Text></Pressable></View>{payments.length ? payments.map((payment: any, index: number) => <View key={payment.id || index} className="flex-row items-center py-2.5 border-b border-slate-100"><CreditCard size={16} color="#059669" /><View className="flex-1 ml-3"><Text className="text-xs font-bold text-slate-800">{formatINR(payment.amount)}</Text><Text className="text-[11px] text-slate-500 mt-0.5">{formatDate(payment.paymentDate || payment.date)} • {payment.paymentMethod || 'Payment'}</Text></View><Badge text={payment.status || 'Successful'} tone="green" /></View>) : <EmptyState message="No payments recorded." />}</Card><Card><Text className="text-sm font-extrabold text-slate-900 mb-2">Site expenses</Text>{expenses.length ? expenses.map((expense: any, index: number) => <View key={expense.id || index} className="flex-row justify-between py-2.5 border-b border-slate-100"><View className="flex-1"><Text className="text-xs font-bold text-slate-800">{expense.expenseName || expense.name || expense.expenseCategory || 'Expense'}</Text><Text className="text-[11px] text-slate-500 mt-0.5">{expense.vendor || 'Internal'} • {formatDate(expense.date)}</Text></View><Text className="text-xs font-bold text-rose-600">{formatINR(expense.amount)}</Text></View>) : <EmptyState message="No expenses recorded." />}</Card></>;
}

function Activity({ data }: { data: { invoices: any[]; warranties: any[]; complaints: any[]; documents: any[] } }) {
  return <><Card><Text className="text-sm font-extrabold text-slate-900 mb-3">Invoices & warranties</Text><DetailRow label="Invoices" value={String(data.invoices.length)} /><DetailRow label="Warranty cards" value={String(data.warranties.length)} /><DetailRow label="Documents" value={String(data.documents.length)} /></Card><Card><Text className="text-sm font-extrabold text-slate-900 mb-3">Service tickets</Text>{data.complaints.length ? data.complaints.map((complaint: any, index: number) => <View key={complaint.id || index} className="flex-row items-center py-2.5 border-b border-slate-100"><Ticket size={16} color="#e11d48" /><View className="flex-1 ml-3"><Text className="text-xs font-bold text-slate-800">{complaint.subject || 'Service request'}</Text><Text className="text-[11px] text-slate-500 mt-0.5">{complaint.priority || 'Medium'} priority</Text></View><Badge text={complaint.status || 'Open'} tone="rose" /></View>) : <Text className="text-xs text-slate-400">No service tickets for this project.</Text>}</Card></>;
}
