import React, { useState } from 'react';
import { Alert, Pressable, Text } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../../src/lib/api';
import { useFetch } from '../../../src/hooks/useFetch';
import { Badge, Card, ChoiceField, DetailRow, EmptyState, ErrorState, FormField, HeaderButton, Loading, PrimaryButton, Screen } from '../../../src/components/ui';
import { formatDate } from '../../../src/lib/formatters';
import { useAuth } from '../../../src/context/AuthContext';

export default function LeadDetailScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const { hasPermission } = useAuth(); const state = useFetch(() => api.getLead(String(id)), [id]); const [type, setType] = useState('Call'); const [summary, setSummary] = useState(''); const [nextDate, setNextDate] = useState(''); const [saving, setSaving] = useState(false); const item = state.data?.lead;
  const add = async () => { if (!summary.trim()) return; setSaving(true); try { await api.createLeadFollowUp(String(id), { interactionType: type as any, summary, nextFollowUpDate: nextDate || undefined }); setSummary(''); setNextDate(''); await state.reload(); } catch (e: any) { Alert.alert('Could not add follow-up', e.message); } finally { setSaving(false); } };
  const remove = () => Alert.alert('Delete lead?', 'This also removes its follow-up history.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await api.deleteLead(String(id)); router.back(); } catch (e: any) { Alert.alert('Could not delete lead', e.message); } } }]);
  return <Screen title={item?.prospectName || 'Lead'} subtitle={item?.customId} onBack={() => router.back()} action={item && hasPermission('leads.manage') ? <HeaderButton label="Edit" onPress={() => router.push({ pathname: '/lead-form', params: { id: item.id } })} /> : undefined} refreshing={state.isRefreshing} onRefresh={state.refresh}>{state.isLoading ? <Loading /> : state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : item ? <><Card><Badge text={item.status} tone={item.status === 'Won' ? 'green' : item.status === 'Lost' ? 'rose' : 'amber'} /><DetailRow label="Phone" value={item.phone} /><DetailRow label="Email" value={item.email} /><DetailRow label="Location" value={`${item.city}, ${item.state}`} /><DetailRow label="Source" value={item.leadSource} /><DetailRow label="Proposed" value={item.proposedCapacityKw ? `${item.proposedCapacityKw} kW` : undefined} />{hasPermission('leads.manage') ? <Pressable onPress={remove} className="mt-3 self-end"><Text className="text-xs font-semibold text-rose-600">Delete Lead</Text></Pressable> : null}</Card>{hasPermission('leads.manage') ? <Card><Text className="mb-3 text-xs font-bold text-slate-500">ADD FOLLOW-UP</Text><ChoiceField label="Interaction" value={type} options={['Call', 'WhatsApp', 'Site Visit', 'Meeting', 'Email', 'Note']} onChange={setType} /><FormField label="Summary" value={summary} onChangeText={setSummary} multiline required /><FormField label="Next follow-up date" value={nextDate} onChangeText={setNextDate} placeholder="YYYY-MM-DD" /><PrimaryButton label={saving ? 'Saving…' : 'Add Follow-up'} onPress={() => void add()} disabled={saving || !summary.trim()} /></Card> : null}<Text className="mb-2 mt-2 px-1 text-xs font-bold text-slate-500">FOLLOW-UP HISTORY</Text>{!state.data?.followUps.length ? <EmptyState message="No follow-ups yet." /> : state.data.followUps.map(follow => <Card key={follow.id}><Badge text={follow.interactionType} /><Text className="mt-2 text-sm text-slate-700">{follow.summary}</Text><Text className="mt-2 text-[10px] text-slate-400">{formatDate(follow.createdAt)}{follow.nextFollowUpDate ? ` · Next ${formatDate(follow.nextFollowUpDate)}` : ''}</Text></Card>)}</> : null}</Screen>;
}
