import React from 'react';
import { Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { useFetch } from '../../src/hooks/useFetch';
import { Badge, Card, DetailRow, EmptyState, ErrorState, Loading, Screen, StatCard } from '../../src/components/ui';
import { formatDate, formatINR } from '../../src/lib/formatters';

export default function BillingScreen() {
  const router = useRouter(); const { tenantId } = useLocalSearchParams<{ tenantId?: string }>(); const state = useFetch(() => tenantId ? api.getTenantBilling(String(tenantId)) : api.getBilling(), [tenantId]); const sub = state.data?.subscription; const invoices = state.data?.invoices ?? []; const meters = state.data?.meters ?? [];
  return <Screen title="Subscription Billing" subtitle="Plan, invoices, and usage limits" onBack={() => router.back()} refreshing={state.isRefreshing} onRefresh={state.refresh}>{state.isLoading ? <Loading /> : state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : <>{sub ? <><StatCard label="Recurring Amount" value={formatINR(sub.unitAmount)} hint={`per ${sub.billingInterval}`} accent="text-emerald-700" /><Card><View className="mb-2"><Badge text={sub.status} tone={sub.status === 'active' ? 'green' : sub.status === 'past_due' || sub.status === 'unpaid' ? 'rose' : 'amber'} /></View><DetailRow label="Plan" value={sub.planTier} /><DetailRow label="Period start" value={formatDate(sub.currentPeriodStart)} /><DetailRow label="Period end" value={formatDate(sub.currentPeriodEnd)} /><DetailRow label="Cancel at end" value={sub.cancelAtPeriodEnd ? 'Yes' : 'No'} /></Card></> : <EmptyState message="No gateway subscription record is configured for this tenant." />}<Text className="mb-2 mt-2 px-1 text-xs font-bold text-slate-500">USAGE METERS</Text>{meters.length === 0 ? <EmptyState message="No usage meters recorded." /> : meters.map(item => <Card key={item.id}><View className="flex-row justify-between"><Text className="text-sm font-bold text-slate-900">{item.metricKey}</Text><Text className="text-sm font-bold text-slate-700">{item.currentValue} / {item.maxLimit}</Text></View><View className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><View className="h-2 rounded-full bg-amber-500" style={{ width: `${Math.min(100, Math.max(2, item.maxLimit ? item.currentValue / item.maxLimit * 100 : 0))}%` }} /></View></Card>)}<Text className="mb-2 mt-2 px-1 text-xs font-bold text-slate-500">INVOICES</Text>{invoices.length === 0 ? <EmptyState message="No subscription invoices recorded." /> : invoices.map(item => <Card key={item.id}><View className="flex-row justify-between gap-3"><View><Text className="text-sm font-bold text-slate-900">{item.invoiceNumber}</Text><Text className="mt-1 text-xs text-slate-500">{formatDate(item.billingDate)}</Text></View><Badge text={item.status} tone={item.status === 'paid' ? 'green' : item.status === 'uncollectible' ? 'rose' : 'amber'} /></View><Text className="mt-3 text-lg font-bold text-slate-900">{formatINR(item.amountDue)}</Text></Card>)}</>}</Screen>;
}
