import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Badge, Card, EmptyState, ErrorState, FormField, HeaderButton, Loading, OptionField, Screen, StatCard } from '../../src/components/ui';
import { formatDate } from '../../src/lib/formatters';
import { useAuth } from '../../src/context/AuthContext';

export default function DiscomScreen() {
  const router = useRouter(); const { hasPermission } = useAuth(); const [projects, setProjects] = useState<any[]>([]); const [projectId, setProjectId] = useState(''); const [stages, setStages] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [expanded, setExpanded] = useState<string | null>(null); const [query, setQuery] = useState('');
  const loadStages = async (value: string) => { setProjectId(value); if (!value) return setStages([]); try { setError(''); setStages((await api.getDiscomStages(value)).stages); } catch (e: any) { setError(e.message); } };
  useEffect(() => { api.getProjects({ limit: '100' }).then(async result => { setProjects(result.projects); if (result.projects[0]) await loadStages(result.projects[0].id); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  const update = (item: any, status: string) => Alert.alert('Update stage?', `${item.stageName} → ${status}`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Update', onPress: async () => { try { await api.updateDiscomStageStatus(item.id, { status, approvalDate: status === 'Approved' ? new Date().toISOString().slice(0, 10) : undefined } as any); await loadStages(projectId); } catch (e: any) { Alert.alert('Could not update stage', e.message); } } }]);
  const visible = useMemo(() => stages.filter(item => item.stageName.toLowerCase().includes(query.toLowerCase())), [stages, query]); const approved = stages.filter(item => item.status === 'Approved').length;
  return <Screen title="DISCOM Liaison" subtitle="Approvals, inspection, and net metering" onBack={() => router.back()} action={hasPermission('discom.manage') && projectId ? <HeaderButton label="Add stage" onPress={() => router.push({ pathname: '/discom-form', params: { projectId } })} /> : undefined}>
    {loading ? <Loading /> : error ? <ErrorState message={error} /> : <><Card><OptionField label="Project" value={projectId} onChange={value => void loadStages(value)} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /></Card><View className="flex-row gap-3"><View className="flex-1"><StatCard label="Stages" value={String(stages.length)} /></View><View className="flex-1"><StatCard label="Approved" value={`${approved}/${stages.length || 0}`} accent="text-emerald-700" /></View></View><FormField label="Search stages" value={query} onChangeText={setQuery} placeholder="Feasibility, inspection, subsidy..." /><Card><Text className="text-xs font-extrabold uppercase tracking-wide text-slate-500">Installation liaison progress</Text><View className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><View className="h-full rounded-full bg-emerald-500" style={{ width: `${stages.length ? (approved / stages.length) * 100 : 0}%` }} /></View><Text className="mt-2 text-xs text-slate-500">{approved} of {stages.length} milestones approved</Text></Card>{visible.length === 0 ? <EmptyState message="No DISCOM stages for this project." /> : visible.map((item, index) => <Card key={item.id}><Pressable onPress={() => setExpanded(expanded === item.id ? null : item.id)}><View className="flex-row items-center gap-3"><View className={`h-8 w-8 items-center justify-center rounded-full ${item.status === 'Approved' ? 'bg-emerald-100' : 'bg-amber-100'}`}><Text className="text-xs font-extrabold text-slate-700">{index + 1}</Text></View><Text className="flex-1 text-sm font-bold text-slate-900">{item.stageName}</Text><Badge text={item.status} tone={item.status === 'Approved' ? 'green' : item.status === 'Rejected' ? 'rose' : 'amber'} /></View></Pressable>{item.applicationReferenceNo ? <Text className="mt-2 ml-11 text-xs text-slate-500">Ref: {item.applicationReferenceNo}</Text> : null}{item.submissionDate ? <Text className="mt-1 ml-11 text-xs text-slate-500">Submitted {formatDate(item.submissionDate)}</Text> : null}{expanded === item.id ? <View className="mt-3 border-t border-slate-100 pt-3"><Text className="text-xs text-slate-600">Officer: {item.discomOfficerName || 'Not assigned'}</Text><Text className="mt-1 text-xs text-slate-600">Remarks: {item.remarks || 'No remarks'}</Text>{hasPermission('discom.manage') ? <View className="mt-3 flex-row justify-end gap-4">{item.status !== 'Approved' ? <Pressable onPress={() => update(item, 'Approved')}><Text className="text-xs font-bold text-emerald-700">Approve</Text></Pressable> : null}{item.status !== 'Rejected' ? <Pressable onPress={() => update(item, 'Rejected')}><Text className="text-xs font-bold text-rose-600">Reject</Text></Pressable> : null}{item.status !== 'On Hold' ? <Pressable onPress={() => update(item, 'On Hold')}><Text className="text-xs font-bold text-amber-700">Hold</Text></Pressable> : null}</View> : null}</View> : null}</Card>)}</>}
  </Screen>;
}
