import React, { useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, FormField, PrimaryButton, Screen } from '../../src/components/ui';

const names = ['Feasibility Application Submitted', 'Feasibility Approved', 'Estimate Generated & Paid', 'Work Execution Submitted (WCR)', 'Safety Inspection / CEIG Inspection', 'Bi-directional Net-Meter Testing', 'Net-Meter Installed on Site', 'Joint Inspection Report (JIR) Signed', 'Subsidy / DBT Portal Claim Dispatched', 'Subsidy Disbursed to Customer'];
export default function DiscomFormScreen() {
  const router = useRouter(); const { projectId } = useLocalSearchParams<{ projectId: string }>(); const [saving, setSaving] = useState(false); const [form, setForm] = useState<any>({ stageName: names[0], status: 'Pending', submissionDate: new Date().toISOString().slice(0, 10), approvalDate: '', applicationReferenceNo: '', discomOfficerName: '', remarks: '' }); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value })); const save = async () => { setSaving(true); try { await api.createDiscomStage(String(projectId), form); router.back(); } catch (e: any) { Alert.alert('Could not create stage', e.message); } finally { setSaving(false); } };
  return <Screen title="Add DISCOM Stage" subtitle="Project approval milestone" onBack={() => router.back()}><Card><ChoiceField label="Stage" value={form.stageName} options={names} onChange={set('stageName')} /><ChoiceField label="Status" value={form.status} options={['Pending', 'In Progress', 'Approved', 'Rejected', 'On Hold']} onChange={set('status')} /><FormField label="Submission date" value={form.submissionDate} onChangeText={set('submissionDate')} /><FormField label="Approval date" value={form.approvalDate} onChangeText={set('approvalDate')} /><FormField label="Application reference" value={form.applicationReferenceNo} onChangeText={set('applicationReferenceNo')} /><FormField label="DISCOM officer" value={form.discomOfficerName} onChangeText={set('discomOfficerName')} /><FormField label="Remarks" value={form.remarks} onChangeText={set('remarks')} multiline /><PrimaryButton label={saving ? 'Saving…' : 'Add Stage'} onPress={() => void save()} disabled={saving} /></Card></Screen>;
}
