import React, { useEffect, useState } from 'react';
import { Alert, Pressable, Text } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { formatFileSize } from '../../src/lib/formatters';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function DocumentFormScreen() {
  const router = useRouter(); const [projects, setProjects] = useState<any[]>([]); const [form, setForm] = useState<any>({ projectId: '', name: '', category: 'Other' }); const [file, setFile] = useState<DocumentPicker.DocumentPickerAsset | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.getProjects({ limit: '100' }).then(data => setProjects(data.projects)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const pick = async () => { const result = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: true, type: '*/*' }); if (!result.canceled) { const asset = result.assets[0]; setFile(asset); if (!form.name) setForm((current: any) => ({ ...current, name: asset.name.replace(/\.[^.]+$/, '') })); } };
  const save = async () => { if (!form.projectId || !form.name.trim() || !file) { Alert.alert('Missing details', 'Project, document name, and a file are required.'); return; } setSaving(true); try { const uploaded = await api.uploadFile({ uri: file.uri, name: file.name, mimeType: file.mimeType }); await api.createDocument({ ...form, fileId: uploaded.fileId, fileName: uploaded.fileName, fileSize: uploaded.fileSize, fileMime: uploaded.mimeType }); router.back(); } catch (e: any) { Alert.alert('Could not upload document', e.message); } finally { setSaving(false); } };
  return <Screen title="Upload Document" subtitle="Attach a project file or certificate" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Project *" value={form.projectId} onChange={set('projectId')} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /><FormField label="Document name" value={form.name} onChangeText={set('name')} required /><ChoiceField label="Category" value={form.category} options={['Agreement', 'Quotation', 'Installation Report', 'Site Survey', 'UPPCL Document', 'Net Metering', 'Completion Certificate', 'Payment Receipt', 'Other']} onChange={set('category')} /><Pressable onPress={() => void pick()} className="border border-dashed border-slate-300 bg-slate-50 rounded-xl p-4 mb-4 items-center"><Text className="text-sm font-semibold text-slate-700">{file ? file.name : 'Choose File'}</Text>{file?.size ? <Text className="text-xs text-slate-400 mt-1">{formatFileSize(file.size)}</Text> : null}</Pressable><PrimaryButton label={saving ? 'Uploading…' : 'Upload Document'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
