import React, { useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, FormField, PrimaryButton, Screen } from '../../src/components/ui';

export default function EmployeeFormScreen() {
  const router = useRouter(); const [form, setForm] = useState<any>({ name: '', email: '', phone: '', role: 'Solar Technician', department: 'Operations', employmentType: 'Full-Time', joiningDate: new Date().toISOString().slice(0, 10), baseSalary: '', bankAccount: '', bankName: '', ifscCode: '', status: 'Active', notes: '' }); const [saving, setSaving] = useState(false); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.name.trim() || !form.role || form.baseSalary === '') { Alert.alert('Missing details', 'Name, role, and base salary are required.'); return; } setSaving(true); try { await api.createEmployee({ ...form, baseSalary: Number(form.baseSalary) }); router.back(); } catch (e: any) { Alert.alert('Could not add employee', e.message); } finally { setSaving(false); } };
  return <Screen title="Add Employee" subtitle="Payroll and bank information" onBack={() => router.back()}><Card><FormField label="Full name" value={form.name} onChangeText={set('name')} required /><FormField label="Email" value={form.email} onChangeText={set('email')} keyboardType="email-address" /><FormField label="Phone" value={form.phone} onChangeText={set('phone')} keyboardType="phone-pad" /><ChoiceField label="Role" value={form.role} options={['Solar EPC Engineer', 'Site Supervisor', 'Solar Technician', 'Electrician', 'Sales & Marketing', 'Liaison Officer', 'Operations Manager', 'Helper / Laborer', 'Accountant']} onChange={set('role')} /><FormField label="Department" value={form.department} onChangeText={set('department')} /><ChoiceField label="Employment type" value={form.employmentType} options={['Full-Time', 'Contract', 'Daily Wage', 'Commission']} onChange={set('employmentType')} /><FormField label="Joining date" value={form.joiningDate} onChangeText={set('joiningDate')} /><FormField label="Base salary" value={form.baseSalary} onChangeText={set('baseSalary')} keyboardType="numeric" required /><FormField label="Bank name" value={form.bankName} onChangeText={set('bankName')} /><FormField label="Bank account" value={form.bankAccount} onChangeText={set('bankAccount')} keyboardType="numeric" /><FormField label="IFSC code" value={form.ifscCode} onChangeText={set('ifscCode')} /><FormField label="Notes" value={form.notes} onChangeText={set('notes')} multiline /><PrimaryButton label={saving ? 'Saving…' : 'Add Employee'} onPress={() => void save()} disabled={saving} /></Card></Screen>;
}
