import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function FieldOperationFormScreen() {
  const router = useRouter(); const { mode = 'attendance' } = useLocalSearchParams<{ mode?: string }>(); const [employees, setEmployees] = useState<any[]>([]); const [projects, setProjects] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [form, setForm] = useState<any>({ employeeId: '', date: new Date().toISOString().slice(0, 10), status: 'Present', assignedProjectId: '', notes: '', projectId: '', reportDate: new Date().toISOString().slice(0, 10), structureMountingProgressPct: '0', panelInstallationProgressPct: '0', wiringInverterProgressPct: '0', laborCountOnSite: '0', workCompletedToday: '', blockersOrDelays: '', weatherConditions: '' });
  useEffect(() => { Promise.all([api.getEmployees({ limit: '100' }), api.getProjects({ limit: '100' })]).then(([e, p]) => { setEmployees(e.employees); setProjects(p.projects); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); try { if (mode === 'dpr') { if (!form.projectId || !form.workCompletedToday.trim()) throw new Error('Project and completed work are required.'); await api.createDpr(form.projectId, form); } else { if (!form.employeeId) throw new Error('Employee is required.'); await api.punchIn(form); } router.back(); } catch (e: any) { Alert.alert('Could not save field record', e.message); } finally { setSaving(false); } };
  return <Screen title={mode === 'dpr' ? 'Daily Progress Report' : 'Attendance Punch-in'} subtitle="On-site execution tracking" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card>{mode === 'dpr' ? <><OptionField label="Project *" value={form.projectId} onChange={set('projectId')} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /><FormField label="Report date" value={form.reportDate} onChangeText={set('reportDate')} /><FormField label="Structure progress (%)" value={form.structureMountingProgressPct} onChangeText={set('structureMountingProgressPct')} keyboardType="numeric" /><FormField label="Panel installation (%)" value={form.panelInstallationProgressPct} onChangeText={set('panelInstallationProgressPct')} keyboardType="numeric" /><FormField label="Wiring / inverter (%)" value={form.wiringInverterProgressPct} onChangeText={set('wiringInverterProgressPct')} keyboardType="numeric" /><FormField label="Labor count" value={form.laborCountOnSite} onChangeText={set('laborCountOnSite')} keyboardType="numeric" /><FormField label="Work completed today" value={form.workCompletedToday} onChangeText={set('workCompletedToday')} multiline required /><FormField label="Blockers / delays" value={form.blockersOrDelays} onChangeText={set('blockersOrDelays')} multiline /><FormField label="Weather" value={form.weatherConditions} onChangeText={set('weatherConditions')} /></> : <><OptionField label="Employee *" value={form.employeeId} onChange={set('employeeId')} options={employees.filter(item => item.status === 'Active').map(item => ({ value: item.id, label: `${item.name} · ${item.role}` }))} /><FormField label="Date" value={form.date} onChangeText={set('date')} /><ChoiceField label="Status" value={form.status} options={['Present', 'Absent', 'Half Day', 'On Leave', 'Holiday', 'Site Duty']} onChange={set('status')} /><OptionField label="Assigned project" value={form.assignedProjectId} onChange={set('assignedProjectId')} options={[{ value: '', label: 'No project' }, ...projects.map(item => ({ value: item.id, label: item.projectName }))]} /><FormField label="Notes" value={form.notes} onChangeText={set('notes')} multiline /></>}<PrimaryButton label={saving ? 'Saving…' : 'Save Record'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
