import React from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { useFetch } from '../../src/hooks/useFetch';
import { Badge, Card, EmptyState, ErrorState, HeaderButton, Loading, Screen, StatCard } from '../../src/components/ui';
import { formatDate } from '../../src/lib/formatters';
import { useAuth } from '../../src/context/AuthContext';

export default function FieldOperationsScreen() {
  const router = useRouter(); const { hasPermission } = useAuth(); const month = new Date().toISOString().slice(0, 7); const state = useFetch(async () => { const [attendance, employees] = await Promise.all([api.getAttendance(month), api.getEmployees({ limit: '100' })]); return { attendance, employees: employees.employees }; }); const records = state.data?.attendance.records ?? []; const names = new Map((state.data?.employees ?? []).map(item => [item.id, item.name]));
  const punchOut = (item: any) => Alert.alert('Punch out?', 'This records an 8-hour working day.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Punch Out', onPress: async () => { try { await api.punchOut(item.id, { workingHours: 8 }); await state.reload(); } catch (e: any) { Alert.alert('Could not punch out', e.message); } } }]);
  return <Screen title="Field Operations" subtitle={`Attendance · ${month}`} onBack={() => router.back()} action={hasPermission('attendance.manage') ? <HeaderButton label="Punch" onPress={() => router.push({ pathname: '/field-operation-form', params: { mode: 'attendance' } })} /> : undefined} refreshing={state.isRefreshing} onRefresh={state.refresh}>{state.isLoading ? <Loading /> : state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : <><View className="flex-row gap-3"><View className="flex-1"><StatCard label="Records" value={String(records.length)} /></View><View className="flex-1"><StatCard label="Present" value={String(records.filter(item => item.status === 'Present' || item.status === 'Site Duty').length)} accent="text-emerald-700" /></View></View>{hasPermission('attendance.manage') ? <Card><HeaderButton label="Submit Daily Progress Report" onPress={() => router.push({ pathname: '/field-operation-form', params: { mode: 'dpr' } })} /></Card> : null}{records.length === 0 ? <EmptyState message="No attendance records this month." /> : records.map(item => <Card key={item.id}><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className="text-sm font-bold text-slate-900">{names.get(item.employeeId) || item.employeeId}</Text><Text className="mt-1 text-xs text-slate-500">{formatDate(item.date)}{item.workingHours ? ` · ${item.workingHours} hours` : ''}</Text></View><Badge text={item.status} tone={item.status === 'Present' || item.status === 'Site Duty' ? 'green' : 'amber'} /></View>{hasPermission('attendance.manage') && item.punchInTime && !item.punchOutTime ? <Pressable onPress={() => punchOut(item)} className="mt-3 self-end"><Text className="text-xs font-semibold text-blue-700">Punch Out</Text></Pressable> : null}</Card>)}</>}</Screen>;
}
