import React from 'react';
import { Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { useFetch } from '../../src/hooks/useFetch';
import { Badge, Card, EmptyState, ErrorState, HeaderButton, Loading, Screen, StatCard } from '../../src/components/ui';
import { formatDate, formatINR } from '../../src/lib/formatters';
import { useAuth } from '../../src/context/AuthContext';

export default function InventoryScreen() {
  const router = useRouter(); const { hasPermission } = useAuth(); const state = useFetch(() => api.getInventory()); const items = state.data?.items ?? []; const movements = state.data?.movements ?? [];
  return <Screen title="Inventory" subtitle="Stock, dispatches, and reorder levels" onBack={() => router.back()} action={hasPermission('inventory.manage') ? <HeaderButton label="Item" onPress={() => router.push('/inventory-form')} /> : undefined} refreshing={state.isRefreshing} onRefresh={state.refresh}>{state.isLoading ? <Loading /> : state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : <><View className="flex-row gap-3"><View className="flex-1"><StatCard label="Items" value={String(items.length)} /></View><View className="flex-1"><StatCard label="Low Stock" value={String(state.data?.lowStockCount ?? 0)} accent="text-rose-600" /></View></View>{hasPermission('inventory.manage') ? <Card><HeaderButton label="Record Stock Movement" onPress={() => router.push({ pathname: '/inventory-form', params: { mode: 'movement' } })} /><View className="h-2" /><HeaderButton label="Add Project BoQ Item" onPress={() => router.push({ pathname: '/inventory-form', params: { mode: 'boq' } })} /></Card> : null}{items.length === 0 ? <EmptyState message="No inventory items yet." /> : items.map(item => <Card key={item.id}><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className="text-sm font-bold text-slate-900">{item.itemName}</Text><Text className="mt-1 text-xs text-slate-500">{item.itemCode} · {item.category}</Text></View><Badge text={item.currentStock <= item.minimumReorderLevel ? 'Low stock' : 'In stock'} tone={item.currentStock <= item.minimumReorderLevel ? 'rose' : 'green'} /></View><Text className="mt-3 text-xl font-bold text-slate-900">{item.currentStock} <Text className="text-xs font-normal text-slate-400">{item.unitOfMeasure}</Text></Text><Text className="mt-1 text-xs text-slate-500">Cost {formatINR(item.costPricePerUnit)} · Reorder at {item.minimumReorderLevel}</Text></Card>)}<Text className="mb-2 mt-3 px-1 text-xs font-bold text-slate-500">RECENT MOVEMENTS</Text>{movements.slice(0, 10).map(item => <Card key={item.id}><View className="flex-row justify-between"><Badge text={item.movementType.replaceAll('_', ' ')} tone={item.movementType.includes('OUT') || item.movementType.includes('WRITE') ? 'rose' : 'green'} /><Text className="text-xs font-bold text-slate-700">{item.quantity}</Text></View><Text className="mt-2 text-[10px] text-slate-400">{formatDate(item.createdAt)} · Stock {item.previousStock} → {item.resultingStock}</Text></Card>)}</>}</Screen>;
}
