import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { useFetch } from '../../src/hooks/useFetch';
import { Badge, Card, EmptyState, ErrorState, FormField, HeaderButton, Loading, OptionField, Screen, StatCard } from '../../src/components/ui';
import { formatDate, formatINR } from '../../src/lib/formatters';
import { useAuth } from '../../src/context/AuthContext';

const tabs = ['Stock', 'Movements', 'Project BoQ'] as const;
const nextStatus: Record<string, string> = { Planned: 'Partially Dispatched', 'Partially Dispatched': 'Fully Dispatched', 'Fully Dispatched': 'Installed/Consumed' };

export default function InventoryScreen() {
  const router = useRouter(); const { hasPermission } = useAuth(); const state = useFetch(() => api.getInventory()); const [tab, setTab] = useState('Stock'); const [query, setQuery] = useState(''); const [projects, setProjects] = useState<any[]>([]); const [projectId, setProjectId] = useState(''); const [boq, setBoq] = useState<any[]>([]); const [boqError, setBoqError] = useState('');
  const items = state.data?.items ?? []; const movements = state.data?.movements ?? [];
  useEffect(() => { api.getProjects({ limit: '100' }).then(x => { setProjects(x.projects); if (x.projects[0]) setProjectId(x.projects[0].id); }).catch(() => undefined); }, []);
  useEffect(() => { if (!projectId) return; api.getProjectBoq(projectId).then(x => setBoq(x.items)).catch(e => setBoqError(e.message)); }, [projectId]);
  const filtered = useMemo(() => items.filter(item => `${item.itemName} ${item.itemCode} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const advanceBoq = async (item: any) => { const status = nextStatus[item.status]; if (!status) return; try { await api.updateProjectBoqItem(item.id, { status: status as any }); setBoq(current => current.map(entry => entry.id === item.id ? { ...entry, status } : entry)); } catch (e: any) { Alert.alert('Could not update BoQ status', e.message); } };
  return <Screen title="Inventory & BoQ" subtitle="Stock, dispatches, and project material planning" onBack={() => router.back()} action={hasPermission('inventory.manage') ? <HeaderButton label="Add" onPress={() => router.push('/inventory-form')} /> : undefined} refreshing={state.isRefreshing} onRefresh={state.refresh}>
    {state.isLoading ? <Loading /> : state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : <>
      <View className="flex-row gap-3"><View className="flex-1"><StatCard label="Items" value={String(items.length)} /></View><View className="flex-1"><StatCard label="Low Stock" value={String(state.data?.lowStockCount ?? 0)} accent="text-rose-600" /></View></View>
      <View className="mb-3 flex-row rounded-xl bg-slate-100 p-1">{tabs.map(name => <Pressable key={name} onPress={() => setTab(name)} className={`flex-1 rounded-lg px-1 py-2.5 ${tab === name ? 'bg-white' : ''}`}><Text className={`text-center text-[11px] font-bold ${tab === name ? 'text-slate-900' : 'text-slate-500'}`}>{name}</Text></Pressable>)}</View>
      {tab === 'Stock' ? <><FormField label="Search stock" value={query} onChangeText={setQuery} placeholder="Item, code or category" />{hasPermission('inventory.manage') ? <Card><HeaderButton label="Record Stock Movement" onPress={() => router.push({ pathname: '/inventory-form', params: { mode: 'movement' } })} /><View className="h-2" /><HeaderButton label="Add Project BoQ Item" onPress={() => router.push({ pathname: '/inventory-form', params: { mode: 'boq' } })} /></Card> : null}{filtered.length === 0 ? <EmptyState message="No inventory items match this search." /> : filtered.map(item => <Card key={item.id}><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className="text-sm font-bold text-slate-900">{item.itemName}</Text><Text className="mt-1 text-xs text-slate-500">{item.itemCode} · {item.category} · {item.brand || 'Generic'}</Text></View><Badge text={item.currentStock <= item.minimumReorderLevel ? 'Low stock' : 'In stock'} tone={item.currentStock <= item.minimumReorderLevel ? 'rose' : 'green'} /></View><Text className="mt-3 text-xl font-bold text-slate-900">{item.currentStock} <Text className="text-xs font-normal text-slate-400">{item.unitOfMeasure}</Text></Text><Text className="mt-1 text-xs text-slate-500">Cost {formatINR(item.costPricePerUnit)} · Reorder at {item.minimumReorderLevel} · GST {item.gstRatePercent}%</Text></Card>)}</> : null}
      {tab === 'Movements' ? <>{movements.length === 0 ? <EmptyState message="No stock movements yet." /> : movements.map(item => <Card key={item.id}><View className="flex-row justify-between"><Badge text={item.movementType.replaceAll('_', ' ')} tone={item.movementType.includes('OUT') || item.movementType.includes('WRITE') ? 'rose' : 'green'} /><Text className="text-xs font-bold text-slate-700">{item.quantity}</Text></View><Text className="mt-2 text-xs text-slate-600">{item.vendorSupplier || 'Internal movement'} {item.referenceChallanNo ? `· ${item.referenceChallanNo}` : ''}</Text><Text className="mt-1 text-[10px] text-slate-400">{formatDate(item.createdAt)} · Stock {item.previousStock} → {item.resultingStock} · {formatINR(item.totalCost)}</Text></Card>)}</> : null}
      {tab === 'Project BoQ' ? <><Card><OptionField label="Project" value={projectId} onChange={setProjectId} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /></Card>{boqError ? <ErrorState message={boqError} /> : boq.length === 0 ? <EmptyState message="No BoQ items for this project." /> : boq.map(item => <Card key={item.id}><View className="flex-row justify-between gap-2"><View className="flex-1"><Text className="text-sm font-bold text-slate-900">{item.itemName}</Text><Text className="mt-1 text-xs text-slate-500">{item.category} · {formatINR(item.unitCostEstimate)} / {item.unit}</Text></View><Badge text={item.status} tone={item.status === 'Installed/Consumed' || item.status === 'Fully Dispatched' ? 'green' : 'amber'} /></View><View className="mt-3 flex-row border-t border-slate-100 pt-3"><View className="flex-1"><Text className="text-[10px] text-slate-400">PLANNED</Text><Text className="text-sm font-bold">{item.plannedQuantity}</Text></View><View className="flex-1"><Text className="text-[10px] text-slate-400">DISPATCHED</Text><Text className="text-sm font-bold text-blue-700">{item.dispatchedQuantity}</Text></View><View className="flex-1"><Text className="text-[10px] text-slate-400">CONSUMED</Text><Text className="text-sm font-bold text-emerald-700">{item.consumedQuantity}</Text></View></View>{hasPermission('inventory.manage') && nextStatus[item.status] ? <Pressable onPress={() => void advanceBoq(item)} className="mt-3 self-end"><Text className="text-xs font-bold text-blue-700">Advance to {nextStatus[item.status]}</Text></Pressable> : null}{item.notes ? <Text className="mt-2 text-xs text-slate-500">{item.notes}</Text> : null}</Card>)}</> : null}
    </>}
  </Screen>;
}
