import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function InvoiceFormScreen() {
  const router = useRouter(); const [projects, setProjects] = useState<any[]>([]); const [form, setForm] = useState<any>({ projectId: '', invoiceNumber: '', invoiceDate: new Date().toISOString().slice(0, 10), dueDate: '', amount: '', taxAmount: '0', invoiceType: 'Tax Invoice', status: 'Issued', description: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.getProjects({ limit: '100' }).then(data => setProjects(data.projects)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.projectId || !Number(form.amount)) { Alert.alert('Missing details', 'Project and a positive amount are required.'); return; } setSaving(true); try { await api.createInvoice({ ...form, amount: Number(form.amount), taxAmount: Number(form.taxAmount) }); router.back(); } catch (e: any) { Alert.alert('Could not create invoice', e.message); } finally { setSaving(false); } };
  return <Screen title="Create Invoice" subtitle="Issue a customer billing document" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Project *" value={form.projectId} onChange={set('projectId')} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /><FormField label="Invoice number" value={form.invoiceNumber} onChangeText={set('invoiceNumber')} placeholder="Auto-generated when blank" /><FormField label="Invoice date" value={form.invoiceDate} onChangeText={set('invoiceDate')} /><FormField label="Due date" value={form.dueDate} onChangeText={set('dueDate')} /><FormField label="Amount" value={form.amount} onChangeText={set('amount')} keyboardType="numeric" required /><FormField label="Tax amount" value={form.taxAmount} onChangeText={set('taxAmount')} keyboardType="numeric" /><ChoiceField label="Invoice type" value={form.invoiceType} options={['Tax Invoice', 'Proforma', 'Advance Receipt', 'Final Bill']} onChange={set('invoiceType')} /><ChoiceField label="Status" value={form.status} options={['Issued', 'Paid', 'Cancelled']} onChange={set('status')} /><FormField label="Description" value={form.description} onChangeText={set('description')} multiline /><PrimaryButton label={saving ? 'Saving…' : 'Create Invoice'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
