import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, PrimaryButton, Screen } from '../../src/components/ui';

const initial = { prospectName: '', phone: '', email: '', address: '', city: 'Lucknow', state: 'Uttar Pradesh', pincode: '', monthlyElectricityBill: '', sanctionedLoadKw: '', proposedCapacityKw: '', leadSource: 'Other', status: 'New', lostReason: '', notes: '' };
export default function LeadFormScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const [form, setForm] = useState<any>(initial); const [loading, setLoading] = useState(Boolean(id)); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; api.getLead(String(id)).then(result => setForm({ ...initial, ...result.lead, monthlyElectricityBill: String(result.lead.monthlyElectricityBill || ''), sanctionedLoadKw: String(result.lead.sanctionedLoadKw || ''), proposedCapacityKw: String(result.lead.proposedCapacityKw || '') })).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]);
  const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.prospectName.trim() || !form.phone.trim() || !form.city.trim()) return Alert.alert('Missing details', 'Name, phone, and city are required.'); setSaving(true); try { if (id) await api.updateLead(String(id), form); else await api.createLead(form); router.back(); } catch (e: any) { Alert.alert('Could not save lead', e.message); } finally { setSaving(false); } };
  return <Screen title={id ? 'Edit Lead' : 'New Lead'} subtitle="Prospect and solar requirement" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><FormField label="Prospect name" value={form.prospectName} onChangeText={set('prospectName')} required /><FormField label="Phone" value={form.phone} onChangeText={set('phone')} keyboardType="phone-pad" required /><FormField label="Email" value={form.email} onChangeText={set('email')} keyboardType="email-address" /><FormField label="Address" value={form.address} onChangeText={set('address')} multiline /><FormField label="City" value={form.city} onChangeText={set('city')} required /><FormField label="State" value={form.state} onChangeText={set('state')} /><FormField label="Pincode" value={form.pincode} onChangeText={set('pincode')} keyboardType="numeric" /><FormField label="Monthly electricity bill" value={form.monthlyElectricityBill} onChangeText={set('monthlyElectricityBill')} keyboardType="numeric" /><FormField label="Sanctioned load (kW)" value={form.sanctionedLoadKw} onChangeText={set('sanctionedLoadKw')} keyboardType="numeric" /><FormField label="Proposed capacity (kW)" value={form.proposedCapacityKw} onChangeText={set('proposedCapacityKw')} keyboardType="numeric" /><ChoiceField label="Source" value={form.leadSource} options={['Meta Ads', 'Google Ads', 'Website', 'Referral', 'Field Outreach', 'Channel Partner', 'Other']} onChange={set('leadSource')} /><ChoiceField label="Status" value={form.status} options={['New', 'Contacted', 'Site Survey Scheduled', 'Proposal Sent', 'Negotiation', 'Won', 'Lost', 'Disqualified']} onChange={set('status')} />{form.status === 'Lost' ? <FormField label="Lost reason" value={form.lostReason} onChangeText={set('lostReason')} /> : null}<FormField label="Notes" value={form.notes} onChangeText={set('notes')} multiline /><PrimaryButton label={saving ? 'Saving…' : 'Save Lead'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
