import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function PaymentFormScreen() {
  const router = useRouter(); const [projects, setProjects] = useState<any[]>([]); const [form, setForm] = useState<any>({ projectId: '', paymentDate: new Date().toISOString().slice(0, 10), amount: '', paymentMethod: 'Bank Transfer', status: 'Successful', transactionRef: '', notes: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.getProjects({ limit: '100' }).then(data => setProjects(data.projects)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.projectId || !Number(form.amount)) { Alert.alert('Missing details', 'Project and a positive amount are required.'); return; } setSaving(true); try { await api.createPayment({ ...form, amount: Number(form.amount) }); router.back(); } catch (e: any) { Alert.alert('Could not record payment', e.message); } finally { setSaving(false); } };
  return <Screen title="Record Payment" subtitle="Add a customer collection" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Project *" value={form.projectId} onChange={set('projectId')} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /><FormField label="Amount" value={form.amount} onChangeText={set('amount')} keyboardType="numeric" required /><FormField label="Payment date" value={form.paymentDate} onChangeText={set('paymentDate')} /><ChoiceField label="Method" value={form.paymentMethod} options={['Cash', 'UPI', 'Bank Transfer', 'Cheque', 'Card', 'Other']} onChange={set('paymentMethod')} /><ChoiceField label="Status" value={form.status} options={['Successful', 'Pending', 'Failed', 'Refunded']} onChange={set('status')} /><FormField label="Transaction reference" value={form.transactionRef} onChangeText={set('transactionRef')} /><FormField label="Notes" value={form.notes} onChangeText={set('notes')} multiline /><PrimaryButton label={saving ? 'Saving…' : 'Record Payment'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
