import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function PaymentFormScreen() {
  const router = useRouter(); const { customerId, projectId, id } = useLocalSearchParams<{ customerId?: string; projectId?: string; id?: string }>(); const [customers, setCustomers] = useState<any[]>([]); const [projects, setProjects] = useState<any[]>([]); const [form, setForm] = useState<any>({ customerId: customerId || '', projectId: projectId || '', paymentDate: new Date().toISOString().slice(0, 10), amount: '', paymentMethod: 'Bank Transfer', status: 'Successful', transactionRef: '', notes: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.getCustomers({ limit: '200' }), api.getProjects({ limit: '200' }), id ? api.getPayments({ limit: '100' }) : Promise.resolve({ payments: [] })]).then(([cusData, projData, paymentData]) => { setCustomers(cusData.customers); setProjects(projData.projects); const payment = paymentData.payments.find((item: any) => item.id === id); if (payment) { const paymentProject = projData.projects.find((item: any) => item.id === payment.projectId); setForm({ ...payment, amount: String(payment.amount), customerId: paymentProject?.customerId || payment.customerId || '' }); return; } const selectedProject = projectId ? projData.projects.find((item: any) => item.id === projectId) : undefined; const firstProject = selectedProject || projData.projects?.[0]; setForm((current: any) => ({ ...current, customerId: customerId || firstProject?.customerId || cusData.customers?.[0]?.id || '', projectId: projectId || firstProject?.id || '' })); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [customerId, projectId, id]); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const customerProjects = projects.filter(p => p.customerId === form.customerId);
  const setCustomer = (customerId: string) => { const firstProject = projects.find(p => p.customerId === customerId); setForm((current: any) => ({ ...current, customerId, projectId: firstProject?.id || '' })); };
  const save = async () => { if (!form.customerId || !form.projectId || !Number(form.amount)) { Alert.alert('Missing details', 'Customer, project, and a positive amount are required.'); return; } setSaving(true); try { if (id) await api.updatePayment(String(id), { amount: Number(form.amount), paymentDate: form.paymentDate, paymentMethod: form.paymentMethod, status: form.status, transactionRef: form.transactionRef, notes: form.notes }); else await api.createPayment({ ...form, amount: Number(form.amount) }); router.back(); } catch (e: any) { Alert.alert(id ? 'Could not update payment' : 'Could not record payment', e.message); } finally { setSaving(false); } };
  return <Screen title={id ? 'Edit Payment' : 'Record Payment'} subtitle={id ? 'Correct amount, date, method, or reference' : 'Add a customer collection'} onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Customer *" value={form.customerId} onChange={setCustomer} options={customers.map(item => ({ value: item.id, label: `${item.name} · ${item.customId}` }))} disabled={!!id} /><OptionField label="Project *" value={form.projectId} onChange={set('projectId')} options={customerProjects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} disabled={!!id} /><FormField label="Amount" value={String(form.amount)} onChangeText={set('amount')} keyboardType="numeric" required /><FormField label="Payment date" value={form.paymentDate} onChangeText={set('paymentDate')} /><ChoiceField label="Method" value={form.paymentMethod} options={['Cash', 'UPI', 'Bank Transfer', 'Cheque', 'Card', 'Other']} onChange={set('paymentMethod')} /><ChoiceField label="Status" value={form.status} options={['Successful', 'Pending', 'Failed', 'Refunded']} onChange={set('status')} /><FormField label="Transaction reference" value={form.transactionRef} onChangeText={set('transactionRef')} /><FormField label="Notes" value={form.notes} onChangeText={set('notes')} multiline /><PrimaryButton label={saving ? 'Saving…' : id ? 'Save Payment Changes' : 'Record Payment'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
