import React, { useMemo, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { useFetch } from '../../src/hooks/useFetch';
import { formatINR } from '../../src/lib/formatters';
import { Badge, Card, EmptyState, ErrorState, FormField, HeaderButton, Loading, Screen, StatCard } from '../../src/components/ui';
import { useAuth } from '../../src/context/AuthContext';
import { shareCsv } from '../../src/lib/export';

const tabs = ['Payroll', 'Employees', 'Advances'] as const;
function Segments({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  return <View className="mb-3 flex-row rounded-xl bg-slate-100 p-1">{tabs.map(tab => <Pressable key={tab} onPress={() => onChange(tab)} className={`flex-1 rounded-lg px-2 py-2.5 ${value === tab ? 'bg-white' : ''}`}><Text className={`text-center text-xs font-bold ${value === tab ? 'text-slate-900' : 'text-slate-500'}`}>{tab}</Text></Pressable>)}</View>;
}

export default function PayrollScreen() {
  const router = useRouter(); const { hasPermission } = useAuth(); const [tab, setTab] = useState('Payroll'); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All');
  const state = useFetch(async () => { const [payroll, employees, advances] = await Promise.all([api.getPayrollRecords({ limit: '100' }), api.getEmployees({ limit: '100' }), api.getSalaryAdvances({ limit: '100' })]); return { payroll, employees, advances }; });
  const records = state.data?.payroll.records ?? []; const employees = state.data?.employees.employees ?? []; const advances = state.data?.advances.advances ?? []; const summary = state.data?.payroll.summary;
  const filteredRecords = useMemo(() => records.filter(item => `${item.employeeName} ${item.employeeCustomId} ${item.month}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || item.status === status)), [records, query, status]);
  const remove = (kind: 'employee' | 'record', id: string, label: string) => Alert.alert(`Delete ${kind}?`, label, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { if (kind === 'employee') await api.deleteEmployee(id); else await api.deletePayrollRecord(id); await state.reload(); } catch (e: any) { Alert.alert('Delete failed', e.message); } } }]);
  const runBatch = () => { const month = new Date().toISOString().slice(0, 7); Alert.alert('Run batch payroll?', `Generate payroll for ${month} for all active employees.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Run', onPress: async () => { try { await api.runBatchPayroll(month); await state.reload(); } catch (e: any) { Alert.alert('Batch payroll failed', e.message); } } }]); };
  const markPaid = (item: any) => Alert.alert('Mark payroll paid?', `${item.employeeName} · ${item.month}`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Mark Paid', onPress: async () => { try { await api.updatePayrollRecord(item.id, { status: 'Paid', paymentDate: new Date().toISOString().slice(0, 10), paymentMethod: 'Bank Transfer' }); await state.reload(); } catch (e: any) { Alert.alert('Could not settle payroll', e.message); } } }]);
  const exportPayroll = async () => { try { await shareCsv('SolarOS_Payroll', filteredRecords.map(item => ({ Employee: item.employeeName, Month: item.month, Gross: item.grossSalary, Deductions: item.totalDeductions, Net: item.netSalary, Status: item.status }))); } catch (e: any) { Alert.alert('Export failed', e.message); } };
  return <Screen title="Staff Payroll" subtitle="Employees, salaries and settlements" onBack={() => router.back()} action={<View className="flex-row gap-2"><HeaderButton label="Export" onPress={() => void exportPayroll()} /><HeaderButton label="Run" onPress={runBatch} /></View>} refreshing={state.isRefreshing} onRefresh={state.refresh}>
    {state.isLoading ? <Loading /> : state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : <>
      <View className="flex-row gap-3"><View className="flex-1"><StatCard label="Employees" value={String(employees.length)} /></View><View className="flex-1"><StatCard label="Net Payroll" value={formatINR(summary?.totalNet)} accent="text-blue-700" /></View></View>
      <Segments value={tab} onChange={setTab} />
      {tab === 'Payroll' ? <><FormField label="Search payroll" value={query} onChangeText={setQuery} placeholder="Employee, ID or month" /><View className="mt-2 flex-row gap-2">{['All', 'Pending', 'Processing', 'Paid'].map(item => <Pressable key={item} onPress={() => setStatus(item)} className={`rounded-full border px-3 py-1.5 ${status === item ? 'border-blue-600 bg-blue-50' : 'border-slate-200'}`}><Text className={`text-[11px] font-bold ${status === item ? 'text-blue-700' : 'text-slate-500'}`}>{item}</Text></Pressable>)}</View>{filteredRecords.length === 0 ? <EmptyState message="No payroll records match this filter." /> : filteredRecords.map(item => <Card key={item.id}><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className="text-sm font-bold text-slate-900">{item.employeeName}</Text><Text className="mt-1 text-xs text-slate-500">{item.employeeRole} · {item.department} · {item.month}</Text></View><Badge text={item.status} tone={item.status === 'Paid' ? 'green' : 'amber'} /></View><View className="mt-3 flex-row border-t border-slate-100 pt-3"><View className="flex-1"><Text className="text-[10px] text-slate-400">GROSS</Text><Text className="text-xs font-bold">{formatINR(item.grossSalary)}</Text></View><View className="flex-1"><Text className="text-[10px] text-slate-400">DEDUCTIONS</Text><Text className="text-xs font-bold text-rose-600">{formatINR(item.totalDeductions)}</Text></View><View className="flex-1"><Text className="text-[10px] text-slate-400">NET</Text><Text className="text-xs font-bold text-emerald-700">{formatINR(item.netSalary)}</Text></View></View><View className="mt-3 flex-row justify-end gap-4">{hasPermission('payroll.manage') && item.status !== 'Paid' ? <Pressable onPress={() => markPaid(item)}><Text className="text-xs font-bold text-emerald-700">Mark paid</Text></Pressable> : null}{hasPermission('payroll.manage') ? <Pressable onPress={() => remove('record', item.id, `${item.employeeName} · ${item.month}`)}><Text className="text-xs font-bold text-rose-600">Delete</Text></Pressable> : null}</View></Card>)}</> : null}
      {tab === 'Employees' ? <><View className="mb-2 items-end"><HeaderButton label="Add Employee" onPress={() => router.push('/employee-form')} /></View>{employees.length === 0 ? <EmptyState message="No employees yet." /> : employees.map(item => <Card key={item.id}><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className="text-sm font-bold text-slate-900">{item.name}</Text><Text className="mt-1 text-xs text-slate-500">{item.role} · {item.department} · {item.customId}</Text></View><Badge text={item.status} tone={item.status === 'Active' ? 'green' : 'slate'} /></View><Text className="mt-3 text-sm font-bold text-slate-800">{formatINR(item.baseSalary)} base salary</Text>{hasPermission('payroll.manage') ? <View className="mt-3 flex-row justify-end gap-4"><Pressable onPress={() => router.push({ pathname: '/employee-form', params: { id: item.id } })}><Text className="text-xs font-bold text-blue-700">Edit</Text></Pressable><Pressable onPress={() => remove('employee', item.id, item.name)}><Text className="text-xs font-bold text-rose-600">Delete</Text></Pressable></View> : null}</Card>)}</> : null}
      {tab === 'Advances' ? <><View className="mb-2 items-end"><HeaderButton label="Grant Advance" onPress={() => router.push('/salary-advance-form')} /></View>{advances.length === 0 ? <EmptyState message="No salary advances recorded." /> : advances.map(item => <Pressable key={item.id} onPress={() => router.push({ pathname: '/salary-advance-form', params: { id: item.id } })}><Card><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className="text-sm font-bold text-slate-900">{item.employeeName}</Text><Text className="mt-1 text-xs text-slate-500">Recovery {item.recoveryMonth} · {item.reason}</Text></View><Badge text={item.isRecovered ? 'Recovered' : 'Pending'} tone={item.isRecovered ? 'green' : 'amber'} /></View><Text className="mt-3 text-lg font-bold text-amber-700">{formatINR(item.amount)}</Text></Card></Pressable>)}</> : null}
    </>}
  </Screen>;
}
