import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function PayrollRecordFormScreen() {
  const router = useRouter(); const [employees, setEmployees] = useState<any[]>([]); const [form, setForm] = useState<any>({ employeeId: '', month: new Date().toISOString().slice(0, 7), baseSalary: '', hra: '0', siteAllowance: '0', projectCommission: '0', bonus: '0', providentFund: '0', professionalTax: '200', tds: '0', advanceDeduction: '0', leaveDeductions: '0', status: 'Pending', paymentMethod: 'Bank Transfer', transactionRef: '', paymentNotes: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.getEmployees({ limit: '100' }).then(data => setEmployees(data.employees)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.employeeId || !form.month) { Alert.alert('Missing details', 'Employee and payroll month are required.'); return; } setSaving(true); try { const numbers = ['baseSalary', 'hra', 'siteAllowance', 'projectCommission', 'bonus', 'providentFund', 'professionalTax', 'tds', 'advanceDeduction', 'leaveDeductions']; const payload = { ...form }; numbers.forEach(key => { payload[key] = payload[key] === '' ? undefined : Number(payload[key]); }); await api.createPayrollRecord(payload); router.back(); } catch (e: any) { Alert.alert('Could not create payroll', e.message); } finally { setSaving(false); } };
  return <Screen title="Run Payroll" subtitle="Create one employee settlement" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Employee *" value={form.employeeId} onChange={(value) => { const employee = employees.find(item => item.id === value); setForm((current: any) => ({ ...current, employeeId: value, baseSalary: String(employee?.baseSalary ?? '') })); }} options={employees.filter(item => item.status === 'Active').map(item => ({ value: item.id, label: `${item.name} · ${item.customId}` }))} /><FormField label="Month (YYYY-MM)" value={form.month} onChangeText={set('month')} required /><FormField label="Base salary" value={form.baseSalary} onChangeText={set('baseSalary')} keyboardType="numeric" /><FormField label="HRA" value={form.hra} onChangeText={set('hra')} keyboardType="numeric" /><FormField label="Site allowance" value={form.siteAllowance} onChangeText={set('siteAllowance')} keyboardType="numeric" /><FormField label="Commission" value={form.projectCommission} onChangeText={set('projectCommission')} keyboardType="numeric" /><FormField label="Bonus" value={form.bonus} onChangeText={set('bonus')} keyboardType="numeric" /><FormField label="Provident fund" value={form.providentFund} onChangeText={set('providentFund')} keyboardType="numeric" /><FormField label="Professional tax" value={form.professionalTax} onChangeText={set('professionalTax')} keyboardType="numeric" /><FormField label="TDS" value={form.tds} onChangeText={set('tds')} keyboardType="numeric" /><FormField label="Advance deduction" value={form.advanceDeduction} onChangeText={set('advanceDeduction')} keyboardType="numeric" /><FormField label="Leave deductions" value={form.leaveDeductions} onChangeText={set('leaveDeductions')} keyboardType="numeric" /><ChoiceField label="Status" value={form.status} options={['Pending', 'Processing', 'Paid']} onChange={set('status')} /><PrimaryButton label={saving ? 'Saving…' : 'Create Payroll Record'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
