import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

const today = new Date().toISOString().slice(0, 10);
const initial: any = { customerId: '', projectName: '', status: 'Booked', installationAddress: '', city: '', state: '', pincode: '', startDate: today, capacityKw: '', panelsCount: '', panelBrand: '', panelModel: '', inverterBrand: '', inverterModel: '', structureType: '', mountingType: '', installationType: '', netMeteringStatus: '', dealAmount: '', discount: '0', taxGst: '0', bookedProfit: '0', bookingDate: today, notes: '' };
const statuses = ['Lead', 'Booked', 'Planning', 'Material Ordered', 'Installation Scheduled', 'Installation In Progress', 'Installed', 'Inspection Pending', 'Completed', 'On Hold', 'Cancelled'];

export default function ProjectFormScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const [form, setForm] = useState(initial); const [customers, setCustomers] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.getCustomers({ limit: '100' }), id ? api.getProject(String(id)) : Promise.resolve(null)]).then(([customerData, projectData]) => { setCustomers(customerData.customers); if (projectData?.project) setForm({ ...initial, ...projectData.project, capacityKw: String(projectData.project.capacityKw ?? ''), panelsCount: String(projectData.project.panelsCount ?? ''), dealAmount: String(projectData.project.dealAmount ?? ''), discount: String(projectData.project.discount ?? 0), taxGst: String(projectData.project.taxGst ?? 0), bookedProfit: String(projectData.project.bookedProfit ?? 0) }); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]);
  const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.customerId || !form.projectName.trim() || !Number(form.capacityKw) || !Number(form.dealAmount)) { Alert.alert('Missing details', 'Customer, project name, capacity, and deal amount are required.'); return; } setSaving(true); try { const payload = { ...form, capacityKw: Number(form.capacityKw), panelsCount: Number(form.panelsCount), dealAmount: Number(form.dealAmount), discount: Number(form.discount), taxGst: Number(form.taxGst), bookedProfit: Number(form.bookedProfit) }; if (id) await api.updateProject(String(id), payload); else await api.createProject(payload); router.back(); } catch (e: any) { Alert.alert('Could not save project', e.message); } finally { setSaving(false); } };
  return <Screen title={id ? 'Edit Project' : 'New Solar Project'} subtitle="Installation, technical and deal details" onBack={() => router.back()}>
    {loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card>
      <OptionField label="Customer *" value={form.customerId} onChange={set('customerId')} options={customers.map(item => ({ value: item.id, label: `${item.name} · ${item.customId}` }))} />
      <FormField label="Project name" value={form.projectName} onChangeText={set('projectName')} required /><ChoiceField label="Status" value={form.status} options={statuses} onChange={set('status')} /><FormField label="Capacity (kW)" value={form.capacityKw} onChangeText={set('capacityKw')} keyboardType="numeric" required /><FormField label="Panel count" value={form.panelsCount} onChangeText={set('panelsCount')} keyboardType="numeric" /><FormField label="Panel brand" value={form.panelBrand} onChangeText={set('panelBrand')} /><FormField label="Panel model" value={form.panelModel} onChangeText={set('panelModel')} /><FormField label="Inverter brand" value={form.inverterBrand} onChangeText={set('inverterBrand')} /><FormField label="Inverter model" value={form.inverterModel} onChangeText={set('inverterModel')} /><FormField label="Installation address" value={form.installationAddress} onChangeText={set('installationAddress')} multiline /><FormField label="City" value={form.city} onChangeText={set('city')} /><FormField label="State" value={form.state} onChangeText={set('state')} /><FormField label="Pincode" value={form.pincode} onChangeText={set('pincode')} keyboardType="numeric" /><FormField label="Start date (YYYY-MM-DD)" value={form.startDate} onChangeText={set('startDate')} /><FormField label="Deal amount" value={form.dealAmount} onChangeText={set('dealAmount')} keyboardType="numeric" required /><FormField label="Discount" value={form.discount} onChangeText={set('discount')} keyboardType="numeric" /><FormField label="GST amount" value={form.taxGst} onChangeText={set('taxGst')} keyboardType="numeric" /><FormField label="Booked profit" value={form.bookedProfit} onChangeText={set('bookedProfit')} keyboardType="numeric" /><FormField label="Notes" value={form.notes} onChangeText={set('notes')} multiline /><PrimaryButton label={saving ? 'Saving…' : id ? 'Save Changes' : 'Create Project'} onPress={() => void save()} disabled={saving} />
    </Card>}
  </Screen>;
}
