import React, { useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, FormField, PrimaryButton, Screen } from '../../src/components/ui';

const future = () => { const date = new Date(); date.setDate(date.getDate() + 15); return date.toISOString().slice(0, 10); };
export default function QuotationFormScreen() {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [form, setForm] = useState<any>({ title: '', validUntil: future(), systemCapacityKw: '', panelTypeBrand: '', inverterTypeBrand: '', itemName: 'Complete Solar EPC System', quantity: '1', unit: 'System', unitPrice: '', discountAmount: '0', taxGstAmount: '0', status: 'Draft', termsConditions: '' }); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.title.trim() || !form.validUntil || !form.itemName.trim()) return Alert.alert('Missing details', 'Title, validity, and line item are required.'); setSaving(true); try { await api.createQuotation({ ...form, items: [{ itemName: form.itemName, quantity: Number(form.quantity || 1), unit: form.unit, unitPrice: Number(form.unitPrice || 0) }] } as any); router.back(); } catch (e: any) { Alert.alert('Could not create quotation', e.message); } finally { setSaving(false); } };
  return <Screen title="New Quotation" subtitle="Proposal pricing and one primary line item" onBack={() => router.back()}><Card><FormField label="Title" value={form.title} onChangeText={set('title')} required /><FormField label="Valid until" value={form.validUntil} onChangeText={set('validUntil')} required /><FormField label="System capacity (kW)" value={form.systemCapacityKw} onChangeText={set('systemCapacityKw')} keyboardType="numeric" /><FormField label="Panel brand/type" value={form.panelTypeBrand} onChangeText={set('panelTypeBrand')} /><FormField label="Inverter brand/type" value={form.inverterTypeBrand} onChangeText={set('inverterTypeBrand')} /><ChoiceField label="Status" value={form.status} options={['Draft', 'Sent', 'Accepted']} onChange={set('status')} /></Card><Card><FormField label="Line item" value={form.itemName} onChangeText={set('itemName')} required /><FormField label="Quantity" value={form.quantity} onChangeText={set('quantity')} keyboardType="numeric" /><FormField label="Unit" value={form.unit} onChangeText={set('unit')} /><FormField label="Unit price" value={form.unitPrice} onChangeText={set('unitPrice')} keyboardType="numeric" /><FormField label="Discount" value={form.discountAmount} onChangeText={set('discountAmount')} keyboardType="numeric" /><FormField label="GST amount" value={form.taxGstAmount} onChangeText={set('taxGstAmount')} keyboardType="numeric" /><FormField label="Terms and conditions" value={form.termsConditions} onChangeText={set('termsConditions')} multiline /><PrimaryButton label={saving ? 'Saving…' : 'Create Quotation'} onPress={() => void save()} disabled={saving} /></Card></Screen>;
}
