import React, { useEffect, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ErrorState, FormField, Loading, PrimaryButton, Screen } from '../../src/components/ui';
import type { Permission } from '../../src/types';

export default function RoleFormScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const [permissions, setPermissions] = useState<Permission[]>([]); const [form, setForm] = useState<any>({ name: '', description: '', permissionKeys: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.getPermissions(), id ? api.getRoles() : Promise.resolve(null)]).then(([permissionData, roleData]) => { setPermissions(permissionData.permissions); if (id) { const item = roleData?.roles.find(value => value.id === id); if (item) setForm({ name: item.name, description: item.description || '', permissionKeys: item.permissionKeys }); } }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]);
  const toggle = (key: string) => setForm((current: any) => ({ ...current, permissionKeys: current.permissionKeys.includes(key) ? current.permissionKeys.filter((value: string) => value !== key) : [...current.permissionKeys, key] })); const save = async () => { if (!form.name.trim()) { Alert.alert('Missing name', 'Role name is required.'); return; } setSaving(true); try { if (id) await api.updateRole(String(id), form); else await api.createRole(form); router.back(); } catch (e: any) { Alert.alert('Could not save role', e.message); } finally { setSaving(false); } };
  const modules = [...new Set(permissions.map(item => item.module))];
  return <Screen title={id ? 'Edit Role' : 'Create Role'} subtitle="Choose fine-grained permissions" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <><Card><FormField label="Role name" value={form.name} onChangeText={value => setForm((current: any) => ({ ...current, name: value }))} required /><FormField label="Description" value={form.description} onChangeText={value => setForm((current: any) => ({ ...current, description: value }))} multiline /></Card>{modules.map(module => <Card key={module}><Text className="text-xs font-bold text-slate-500 uppercase mb-2">{module}</Text>{permissions.filter(item => item.module === module).map(item => { const active = form.permissionKeys.includes(item.key); return <Pressable key={item.key} onPress={() => toggle(item.key)} className={`p-3 rounded-xl border mb-2 ${active ? 'bg-amber-50 border-amber-300' : 'bg-white border-slate-200'}`}><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className={`text-xs font-semibold ${active ? 'text-amber-900' : 'text-slate-700'}`}>{item.key}</Text><Text className="text-[10px] text-slate-400 mt-1">{item.description}</Text></View><Text className={active ? 'text-amber-700' : 'text-slate-300'}>{active ? '✓' : '○'}</Text></View></Pressable>; })}</Card>)}<PrimaryButton label={saving ? 'Saving…' : id ? 'Save Role' : 'Create Role'} onPress={() => void save()} disabled={saving} /></>}
  </Screen>;
}
