import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function SalaryAdvanceFormScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const [employees, setEmployees] = useState<any[]>([]); const [form, setForm] = useState<any>({ employeeId: '', amount: '5000', disbursedDate: new Date().toISOString().slice(0, 10), reason: 'Festival / Emergency Advance', recoveryMonth: new Date().toISOString().slice(0, 7), isRecovered: 'No', notes: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.getEmployees({ limit: '100' }), id ? api.getSalaryAdvances({ limit: '100' }) : Promise.resolve(null)]).then(([employeeData, advanceData]) => { setEmployees(employeeData.employees); if (id) { const item = advanceData?.advances.find(value => value.id === id); if (item) setForm({ ...item, amount: String(item.amount), isRecovered: item.isRecovered ? 'Yes' : 'No' }); } }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.employeeId || !Number(form.amount) || !form.recoveryMonth) { Alert.alert('Missing details', 'Employee, amount, and recovery month are required.'); return; } setSaving(true); try { const payload = { ...form, amount: Number(form.amount), isRecovered: form.isRecovered === 'Yes' }; if (id) await api.updateSalaryAdvance(String(id), payload); else await api.createSalaryAdvance(payload); router.back(); } catch (e: any) { Alert.alert('Could not save advance', e.message); } finally { setSaving(false); } };
  return <Screen title={id ? 'Edit Salary Advance' : 'Grant Salary Advance'} subtitle="Schedule recovery through payroll" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Employee *" value={form.employeeId} onChange={set('employeeId')} options={employees.map(item => ({ value: item.id, label: `${item.name} · ${item.role}` }))} /><FormField label="Amount" value={form.amount} onChangeText={set('amount')} keyboardType="numeric" required /><FormField label="Disbursal date" value={form.disbursedDate} onChangeText={set('disbursedDate')} /><FormField label="Recovery month" value={form.recoveryMonth} onChangeText={set('recoveryMonth')} required /><FormField label="Reason" value={form.reason} onChangeText={set('reason')} required />{id ? <ChoiceField label="Recovered" value={form.isRecovered} options={['No', 'Yes']} onChange={set('isRecovered')} /> : null}<FormField label="Notes" value={form.notes || ''} onChangeText={set('notes')} multiline /><PrimaryButton label={saving ? 'Saving…' : id ? 'Update Advance' : 'Grant Advance'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
