import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function TeamFormScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const [roles, setRoles] = useState<any[]>([]); const [form, setForm] = useState<any>({ username: '', email: '', roleId: '', password: '', isActive: 'Yes' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.getRoles(), id ? api.getStaffUsers() : Promise.resolve(null)]).then(([roleData, userData]) => { setRoles(roleData.roles); if (id) { const item = userData?.users.find(value => value.id === id); if (item) setForm({ ...form, ...item, isActive: item.isActive ? 'Yes' : 'No' }); } }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.username.trim() || !form.email.trim() || !form.roleId) { Alert.alert('Missing details', 'Username, email, and role are required.'); return; } setSaving(true); try { if (id) await api.updateStaffUser(String(id), { username: form.username, email: form.email, roleId: form.roleId, isActive: form.isActive === 'Yes' }); else { const result = await api.createStaffUser(form); Alert.alert('Staff account created', `Temporary password: ${result.tempPassword}`); } router.back(); } catch (e: any) { Alert.alert('Could not save staff account', e.message); } finally { setSaving(false); } };
  return <Screen title={id ? 'Edit Team Member' : 'Add Team Member'} subtitle="Login and RBAC assignment" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><FormField label="Username" value={form.username} onChangeText={set('username')} required /><FormField label="Email" value={form.email} onChangeText={set('email')} keyboardType="email-address" required /><OptionField label="Role *" value={form.roleId} onChange={set('roleId')} options={roles.map(item => ({ value: item.id, label: `${item.name} · ${item.permissionKeys.length} permissions` }))} />{id ? <ChoiceField label="Active" value={form.isActive} options={['Yes', 'No']} onChange={set('isActive')} /> : <FormField label="Temporary password" value={form.password} onChangeText={set('password')} placeholder="Auto-generated when blank" secureTextEntry />}<PrimaryButton label={saving ? 'Saving…' : id ? 'Save Changes' : 'Create Staff Account'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
