import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

const initial: any = { name: '', slug: '', adminEmail: '', adminPassword: '', planId: '', status: 'active', supportPhone: '', companyTagline: '', legalEntityName: '', gstin: '', pan: '', address: '', city: '', state: '', pincode: '' };
export default function TenantFormScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>(); const [plans, setPlans] = useState<any[]>([]); const [form, setForm] = useState(initial); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.getPlans(), id ? api.getSaaSTenant(String(id)) : Promise.resolve(null)]).then(([planData, tenantData]) => { setPlans(planData.plans.filter(item => item.isActive || item.id === tenantData?.tenant.subscription?.planId)); if (tenantData?.tenant) { const item = tenantData.tenant; setForm({ ...initial, ...item, planId: item.subscription?.planId || '', supportPhone: item.branding?.supportPhone || '', companyTagline: item.branding?.companyTagline || '', legalEntityName: item.businessProfile?.legalEntityName || '', gstin: item.businessProfile?.gstin || '', pan: item.businessProfile?.pan || '', address: item.businessProfile?.address || '', city: item.businessProfile?.city || '', state: item.businessProfile?.state || '', pincode: item.businessProfile?.pincode || '' }); } }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.name.trim() || (!id && (!form.slug.trim() || !form.adminEmail.trim() || !form.planId))) { Alert.alert('Missing details', 'Name, slug, admin email, and plan are required for onboarding.'); return; } setSaving(true); try { if (id) await api.updateSaaSTenant(String(id), { name: form.name, adminEmail: form.adminEmail, status: form.status, branding: { supportPhone: form.supportPhone, companyTagline: form.companyTagline }, businessProfile: { legalEntityName: form.legalEntityName, gstin: form.gstin, pan: form.pan, address: form.address, city: form.city, state: form.state, pincode: form.pincode } } as any); else { const result = await api.createSaaSTenant({ ...form, branding: { supportPhone: form.supportPhone, companyTagline: form.companyTagline }, businessProfile: { legalEntityName: form.legalEntityName, gstin: form.gstin, pan: form.pan, address: form.address, city: form.city, state: form.state, pincode: form.pincode } } as any); Alert.alert('Tenant onboarded', `Admin: ${result.initialCredentials.email}\nPassword: ${result.initialCredentials.tempPassword}`); } router.back(); } catch (e: any) { Alert.alert('Could not save tenant', e.message); } finally { setSaving(false); } };
  return <Screen title={id ? 'Edit Tenant' : 'Onboard Tenant'} subtitle="Company, plan and admin account" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <><Card><FormField label="Tenant name" value={form.name} onChangeText={set('name')} required />{!id ? <FormField label="Subdomain slug" value={form.slug} onChangeText={set('slug')} required /> : null}<FormField label="Admin email" value={form.adminEmail} onChangeText={set('adminEmail')} keyboardType="email-address" required />{!id ? <FormField label="Admin password" value={form.adminPassword} onChangeText={set('adminPassword')} placeholder="Defaults to admin123" secureTextEntry /> : <ChoiceField label="Status" value={form.status} options={['active', 'trial', 'suspended', 'expired']} onChange={set('status')} />}{!id ? <OptionField label="Subscription plan *" value={form.planId} onChange={set('planId')} options={plans.map(item => ({ value: item.id, label: `${item.name} · ₹${item.pricePerMonth}/${item.billingCycle}` }))} /> : null}</Card><Card><FormField label="Legal entity name" value={form.legalEntityName} onChangeText={set('legalEntityName')} /><FormField label="GSTIN" value={form.gstin} onChangeText={set('gstin')} /><FormField label="PAN" value={form.pan} onChangeText={set('pan')} /><FormField label="Address" value={form.address} onChangeText={set('address')} multiline /><FormField label="City" value={form.city} onChangeText={set('city')} /><FormField label="State" value={form.state} onChangeText={set('state')} /><FormField label="Pincode" value={form.pincode} onChangeText={set('pincode')} keyboardType="numeric" /><FormField label="Support phone" value={form.supportPhone} onChangeText={set('supportPhone')} keyboardType="phone-pad" /><FormField label="Company tagline" value={form.companyTagline} onChangeText={set('companyTagline')} /></Card><PrimaryButton label={saving ? 'Saving…' : id ? 'Save Tenant' : 'Onboard Tenant'} onPress={() => void save()} disabled={saving} /></>}
  </Screen>;
}
