import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function TicketFormScreen() {
  const router = useRouter(); const { projectId } = useLocalSearchParams<{ projectId?: string }>(); const [projects, setProjects] = useState<any[]>([]); const [form, setForm] = useState<any>({ projectId: projectId || '', complaintType: 'General Complaint', subject: '', description: '', priority: 'Medium' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.getProjects({ limit: '100' }).then(data => { setProjects(data.projects); if (projectId && data.projects.some((item: any) => item.id === projectId)) setForm((current: any) => ({ ...current, projectId })); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [projectId]); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.projectId || !form.subject.trim() || !form.description.trim()) { Alert.alert('Missing details', 'Project, subject, and description are required.'); return; } setSaving(true); try { await api.createComplaint(form); router.back(); } catch (e: any) { Alert.alert('Could not create ticket', e.message); } finally { setSaving(false); } };
  return <Screen title="New Service Ticket" subtitle="Report an issue for a solar project" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Project *" value={form.projectId} onChange={set('projectId')} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /><ChoiceField label="Issue type" value={form.complaintType} options={['Solar Panel', 'Inverter', 'Battery', 'Wiring', 'Earthing', 'Structure', 'Generation Issue', 'UPPCL/Net Metering', 'Installation', 'General Complaint', 'Other']} onChange={set('complaintType')} /><ChoiceField label="Priority" value={form.priority} options={['Low', 'Medium', 'High', 'Critical']} onChange={set('priority')} /><FormField label="Subject" value={form.subject} onChangeText={set('subject')} required /><FormField label="Description" value={form.description} onChangeText={set('description')} multiline required /><PrimaryButton label={saving ? 'Saving…' : 'Create Ticket'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
