import React, { useEffect, useState } from 'react';
import { Alert } from 'react-native';
import { useRouter } from 'expo-router';
import { api } from '../../src/lib/api';
import { Card, ChoiceField, ErrorState, FormField, Loading, OptionField, PrimaryButton, Screen } from '../../src/components/ui';

export default function WarrantyFormScreen() {
  const router = useRouter(); const [projects, setProjects] = useState<any[]>([]); const [form, setForm] = useState<any>({ projectId: '', itemType: 'Solar Panel', warrantyType: 'Manufacturer', periodYears: '', startDate: new Date().toISOString().slice(0, 10), brand: '', model: '', serialNumber: '', remark: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { api.getProjects({ limit: '100' }).then(data => setProjects(data.projects)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const set = (key: string) => (value: string) => setForm((current: any) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.projectId || !Number(form.periodYears) || !form.startDate) { Alert.alert('Missing details', 'Project, warranty period, and start date are required.'); return; } setSaving(true); try { await api.createWarranty({ ...form, periodYears: Number(form.periodYears) }); router.back(); } catch (e: any) { Alert.alert('Could not add warranty', e.message); } finally { setSaving(false); } };
  return <Screen title="Add Warranty" subtitle="Register equipment coverage" onBack={() => router.back()}>{loading ? <Loading /> : error ? <ErrorState message={error} /> : <Card><OptionField label="Project *" value={form.projectId} onChange={set('projectId')} options={projects.map(item => ({ value: item.id, label: `${item.projectName} · ${item.customId}` }))} /><ChoiceField label="Item type" value={form.itemType} options={['Solar Panel', 'Inverter', 'Battery', 'Structure', 'Wiring/Electrical', 'Other Equipment']} onChange={set('itemType')} /><ChoiceField label="Warranty type" value={form.warrantyType} options={['Standard', 'Performance', 'Manufacturer', 'Extended', 'Workmanship']} onChange={set('warrantyType')} /><FormField label="Period (years)" value={form.periodYears} onChangeText={set('periodYears')} keyboardType="numeric" required /><FormField label="Start date" value={form.startDate} onChangeText={set('startDate')} required /><FormField label="Brand" value={form.brand} onChangeText={set('brand')} /><FormField label="Model" value={form.model} onChangeText={set('model')} /><FormField label="Serial number" value={form.serialNumber} onChangeText={set('serialNumber')} /><FormField label="Remark" value={form.remark} onChangeText={set('remark')} multiline /><PrimaryButton label={saving ? 'Saving…' : 'Add Warranty'} onPress={() => void save()} disabled={saving} /></Card>}</Screen>;
}
